### ISSUE TITLE
Complete repository model

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-models#6]
Depends on #5

Repository needs:
- [ ] Access (private/public)
- [ ] Content (ontology/model/specification)
- [x] many_to_one Namespace

Make the combination of namespace_id and slug unique.

**Comment by phyrog** [comment]
We should also think about the slug of the repository. We could either leave it as is (just the repository name slugified) or include the namespace slug (GitLab does this).

The latter would have the benefit, that the slug alone is unique again (I think this should have an impact on the index performance) as well as benefits for the API (`GET /repositories/some-namespace%2Fsome-repo` instead of some weird `namespace` query parameter fiddeling). Note that the `/` in the slug would be urlencoded to `%2F` in the API call.

**Comment by eugenk** [comment]
I would not encode the slug to `%2F` in the API call. Instead, I would force the (Rails) route to a repository to have a `/` in the `repository_slug` parameter. This can be accomplished with [segment constraints](http://guides.rubyonrails.org/routing.html#segment-constraints).
